flowchart TD
    A[STM32H755ZI MAC] -->|126 PG11/RMII_TX_EN| B[LAN8742A PHY]
    A -->|126 PG11/RMII_TX_EN| B
    A -->|128 PG13/RMII_TXD0| B
    A -->|74 JP PB13/RMII_TXD1| B
    A -->|44 PC4/RMII_RXD0| B
    A -->|45 PC5/RMII_RXD1| B
    A -->|35 PA1/RMII_REF_CLK| B
    A -->|43 JP PA7/RMII_CRS_DV| B