flowchart TD
    B[Read a button] --> |If button pressed| C[Sent myLedOn in UART] 
    C --> B
    A[Main] --> DD
    DD[Check for Device role] --> |if slave| GG[SLave duties] 
    GG --> D
    GG --> B
    DD -->|if master| F
    D[I2C Recieve Inturrupt] --> |When Recieved ON| E[LED On]
    F[USART Recieve Interrupt] --> |When recieved myLedOn| G[Transmit ON in I2C as master]